# dotenv: .env 
# wallet:
#   from_key: ${PRIVATE_KEY}
compiler:
    solc:
        remappings:
            # - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"