name: ERC200-Compile
on: [push]
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
  GITHUB_TOKEN: ${{ secrets.WORKFLOW}}
jobs:
  ERC200-Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install eth-brownie
      - run: npm install ganache
#       - run: brownie pm install OpenZeppelin/openzeppelin-contracts@4.8.0
#       - run: brownie compile
#       - run: brownie test
# On this day, we shall know where the bug comes from.
